name: CI
on:
  push:
    branches:
      - main
      - renovate/*
  pull_request:
    branches:
      - main
      - renovate/*

jobs:
  CI:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: tobysmith568/actions/.github/actions/checkout-pnpm-project@main

      - name: Run Prettier
        run: pnpm exec prettier --check .

      - name: Run Prettier
        run: pnpm exec eslint . --max-warnings 0

      - name: Check Licenses
        run: pnpm exec license-cop

      - name: Build
        run: pnpm run build

      - name: Ensure README.md is up to date
        run: git diff --quiet
